GET http://localhost:3002/users

###

POST http://localhost:3002/signup
Content-Type: application/json

{
    "username": "haoruikun",
    "password": "hrk99828"
}

###
POST http://localhost:3002/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}