GET http://localhost:3002/toggle_bookmark/27

###

POST http://localhost:3002/signup
Content-Type: application/json

{
    "username": "haoruikun",
    "password": "hrk99828"
}

###
POST http://localhost:3002/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
POST http://localhost:3002/dashboard_spending
Content-Type: application/json

{
    "username": "haoruikun",
    "year": 2021,
    "month": 11
}

###
POST http://localhost:3002/all_spending
Content-Type: application/json

{
    "username": "haoruikun"
}

POST http://localhost:3002/record
Content-Type: application/json

{
    "category": "1",
    "amount": 25,
    "reason": "testing",
    "date": "2011-11-11"
}

###
DELETE http://localhost:3002/delete/51
Content-Type: application/json

###

PUT http://localhost:3002/record
Content-Type: application/json

{
    "category": "1",
    "amount": 25,
    "reason": "testing modified",
    "date": "2011-11-11",
    "id": 52
}